src/Entity/Intervention.php
<?php

namespace App\Entity;

use App\Repository\InterventionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InterventionRepository::class)]
class Intervention
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_client = null;

    #[ORM\Column]
    private ?int $id_technicien = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cp = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prix = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdClient(): ?int
    {
        return $this->id_client;
    }

    public function setIdClient(int $id_client): self
    {
        $this->id_client = $id_client;

        return $this;
    }

    public function getIdTechnicien(): ?int
    {
        return $this->id_technicien;
    }

    public function setIdTechnicien(int $id_technicien): self
    {
        $this->id_technicien = $id_technicien;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(?string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

}

src/Form/InterventionType.php
<?php

namespace App\Form;

use App\Entity\Intervention;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InterventionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_client')
            ->add('id_technicien')
            ->add('adresse')
            ->add('cp')
            ->add('ville')
            ->add('date')
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Intervention::class,
        ]);
    }
}

src/Controller/InterventionController.php
<?php

namespace App\Controller;

use App\Entity\Intervention;
use App\Form\InterventionType;
use App\Repository\ClientRepository;
use App\Repository\InterventionRepository;
use App\Repository\TechnicienRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/intervention')]
class InterventionController extends AbstractController
{
    #[Route('/', name: 'app_intervention_index', methods: ['GET'])]
    public function index(InterventionRepository $interventionRepository): Response
    {
        // On va chercher la requête
        $interventionAll = $interventionRepository->findIntervention();

        //dd($interventionAll);

        //dd($interventionCount);

        return $this->render('intervention/index.html.twig', [
            'interventions' => $interventionAll, //On prend la requête et on la met dans intervention
        ]);


    }

    #[Route('/new', name: 'app_intervention_new', methods: ['GET', 'POST'])]
    public function new(Request $request,EntityManagerInterface $entityManager,ClientRepository $clientRepository, TechnicienRepository $technicienRepository): Response
    {

        //Nouveau travailleur
        $intervention = new Intervention();
        $client       = $clientRepository->findAll(); //On trouve toutes les clients
        $technicien   = $technicienRepository->findAll(); //On trouve tous les techniciens


        if ($request->request->get("intervention")) { //Si la requête est bonne alors:

            //On affecte à intervention l'id du client et l'id tech
            $intervention->setIdClient($request->request->get("intervention")["id_client"]);
            $intervention->setIdTechnicien($request->request->get("intervention")["id_technicien"]);
            $dateIntervention = new \DateTime($request->request->get("intervention")["date"]);
            $intervention->setCp($request->request->get("intervention")["cp"]);
            $intervention->setAdresse($request->request->get("intervention")["adresse"]);
            $intervention->setPrix($request->request->get("intervention")["prix"]);
            $intervention->setVille($request->request->get("intervention")["ville"]);
            $intervention->setDate($dateIntervention);

            if ($intervention->getIdClient() && $intervention->getIdTechnicien() &&  $intervention->getVille() &&  $intervention->getAdresse() &&  $intervention->getPrix() &&  $intervention->getCp() && $intervention->getDate()) {

                //On persiste l'objet en base
                $entityManager->persist($intervention);
                //Le flush permet de confirmer le tout
                $entityManager->flush();

                return $this->redirectToRoute('intervention/index.html.twig', [], Response::HTTP_SEE_OTHER);

            }
        }

        //dd($technicien);

        return $this->render('intervention/new.html.twig', [
            'intervention' => $intervention,
            //Type clés index ce qui nous permet apres de jouer avec notamment avec les selects dans les formulaires manuels
            'clients' => $client,
            'techniciens' => $technicien,
        ]);
    }

    #[Route('/{id}', name: 'app_intervention_show', methods: ['GET'])]
    public function show(Intervention $intervention,ClientRepository $clientRepository, TechnicienRepository $technicienRepository): Response
    {

        $client = $clientRepository->findOneBy(['id'=>$intervention->getIdClient()]);

        // Pour le afficher en plus de detail
        // Permet de rechercher via l'id Tech et client de chaque ligne le nom correspondant
        // A rajouter dans TEMPLATE/SHOW.html
        $technicien = $technicienRepository->findOneBy(['id'=>$intervention->getIdTechnicien()]);

        //dd($region);
        return $this->render('intervention/show.html.twig', [
            'intervention' => $intervention,
            'client' => $client,
            'technicien' => $technicien
        ]);
    }

    #[Route('/{id}/edit', name: 'app_intervention_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Intervention $intervention, InterventionRepository $interventionRepository): Response
    {

    }

    #[Route('/{id}', name: 'app_intervention_delete', methods: ['POST'])]
    public function delete(Request $request, Intervention $intervention, InterventionRepository $interventionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$intervention->getId(), $request->request->get('_token'))) {
            $interventionRepository->remove($intervention, true);
        }

        return $this->redirectToRoute('app_intervention_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/intervention/_delete_form.html.twig
<form method="post" action="{{ path('app_intervention_delete', {'id': intervention.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ intervention.id) }}">
    <button class="btn">Delete</button>
</form>

templates/intervention/_form.html.twig
<form name="intervention" method="post">
    <div class="mb-3">
        <label class="form-label required" for="intervention_id_client">Client</label>
        <select id="intervention_id_client" name="intervention[id_client]" class="form-select">

            {% if clients %}
                {# si tu trouve des Clients #}
                {% for client in clients %}

                    {% if client.id == intervention.idClient %} {# Si l'id du visiteur correspond à l'id du travailleur alors #}
                        {% set selectClient = 'selected' %} {# Séléctionner le visiteur #}

                    {% else %}
                        {% set selectClient = '' %} {# Sinon ne rien afficher #}
                    {% endif %}
                    <option value="{{ client.id }}" {{ selectClient }}>{{ client.nom }}</option>

                {% endfor %}
            {% else %}
                <option value="">Aucune donnée trouvée</option>

            {% endif %}

        </select>
    </div>

    <div class="mb-3">
        <label class="form-label required" for="intervention_id_technicien">Technicien</label>
        <select id="intervention_id_technicien" name="intervention[id_technicien]" class="form-select">
            {% if techniciens %}
                {# si tu trouve des secteurs #}
                {% for technicien in techniciens %}
                    {% if technicien.id == intervention.idTechnicien %} {# Si l'id region = id region de intervention #}
                        {% set selectTechnicien = 'selected' %} {# Déclarer une variable. Le selected valide la condition #}

                    {% else %}
                        {% set selectTechnicien = '' %}  {# Vide car la condition n'est pas remplie #}
                    {% endif %}

                    <option value="{{ technicien.id }}" {{ selectTechnicien }}>
                        {{ technicien.nom }}
                    </option>
                    {# Lorsque l'on séléctionne un travailleur, sa région s'affichera direct dans la case du menu déroulant  #}

                {% endfor %}
            {% else %}
                <option value="">Aucune donnée trouvée</option>

            {% endif %}

        </select>
    </div>


    <div id="intervention">
        <div class="mb-3">
            <label for="intervention_adresse" class="form-label required">
                Adresse :
            </label>
            <input type="text" id="intervention_adresse" name="intervention[adresse]" required="required" class="form-control" value="{{ intervention.Adresse }}">
        </div>
        <div class="mb-3">
            <label for="intervention_cp" class="form-label required">
                Cp :
            </label>
            <input type="text" id="intervention_cp" name="intervention[cp]" required="required" class="form-control" value="{{ intervention.Cp }}">
        </div>
        <div class="mb-3">
            <label for="intervention_ville" class="form-label required">
                Ville :
            </label>
            <input type="text" id="intervention_ville" name="intervention[ville]" required="required" class="form-control" value="{{ intervention.Ville }}">
        </div>
        <div class="mb-3">
            <label for="intervention_prix" class="form-label required">
                Prix :
            </label>
            <input type="text" id="intervention_prix" name="intervention[prix]" required="required" class="form-control" value="{{ intervention.Prix }}">
        </div>
        <div class="mb-3">
            <label for="intervention_date" class="form-label required">
                Date
            </label>
            <input type="datetime-local" id="intervention_date" name="intervention[date]" required="required" class="form-control" value="{{ intervention.date|date('Y-m-d\\TH:i')  }}">
        </div>
    </div>

    <button class="btn btn-primary">{{ button_submit|default('Save') }} </button>
</form>

templates/intervention/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Intervention{% endblock %}

{% block body %}
    <h1>Modifier Intervention</h1>

    {{ include('intervention/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('app_intervention_index') }}">Retour aux interventions</a>

{% endblock %}

templates/intervention/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intervention{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
    <h1 class="mb-4">Intervention</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Client</th>
                <th>Adresse</th>
                <th>Cp</th>
                <th>Ville</th>
                <th>Date</th>
                <th>Prix</th>
                <th>Technicien</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for intervention in interventions %}
            <tr>
                <td>{{ intervention['nom'] }}</td>
                <td>{{ intervention[0].adresse }}</td>
                <td>{{ intervention[0].cp }}</td>
                <td>{{ intervention[0].ville }}</td>
                <td>{{ intervention[0].date ? intervention[0].date|date('Y-m-d') : '' }}</td>
                <td>{{ intervention[0].prix }}</td>
                <td>{{ intervention['prenom'] }}</td>
                <td>
                    <a class="btn btn-primary mr-2" href="{{ path('app_intervention_show', {'id': intervention[0].id}) }}">Voir +</a>
                    <a class="btn btn-success" href="{{ path('app_intervention_edit', {'id': intervention[0].id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune intervention</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('app_intervention_new') }}">Create new</a>
{% endblock %}

templates/intervention/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Intervention{% endblock %}

{% block body %}
    <h1>Create new Intervention</h1>

    {{ include('intervention/_form.html.twig') }}

    <a class="btn btn-primary" href="{{ path('app_intervention_index') }}" class="btn btn-primary">Retourner a la liste</a>
{% endblock %}

templates/intervention/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intervention{% endblock %}

{% block body %}
    <h1>Intervention {{ client.nom }} </h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Client</th>
                <td>{{ client.nom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ intervention.adresse }}</td>
            </tr>
            <tr>
                <th>Cp</th>
                <td>{{ intervention.cp }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ intervention.ville }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ intervention.date ? intervention.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ intervention.prix }}</td>
            </tr>
            <tr>
                <th>Technicien</th>
                <td>{{ technicien.prenom }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn-primary btn" href="{{ path('app_intervention_index') }}">Retourner à la liste des interventions</a>
    <br>
    <br>

    <a class="btn-primary btn" href="{{ path('app_intervention_edit', {'id': intervention.id}) }}">Modifier</a>
{% endblock %}